name: site

on:
  push:
    paths-ignore:
    - 'src/**'
    - 'img/**'
    - '*.md'
    - '*.txt'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Install .NET 5.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: Build web site
      run: |
          dotnet tool install --global lunet
          lunet --input-dir site build 

    - name: Deploy web site
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./site/.lunet/build/www